My-Little-Forum/mylittleforum

- includes/admin.inc.php
- includes/main.inc.php
- includes/register.inc.php
- index.php
- themes/default/main.tpl
- themes/default/subtemplates/admin.inc.tpl
- themes/default/subtemplates/register.inc.tpl
- CSRF protection
- Relative Path Overwrite issues
> Vulnerabilities

- includes/admin.inc.php
- includes/contact.inc.php
- includes/entry.inc.php
- includes/posting.inc.php
- includes/user.inc.php
Fix: context sensitive escaping for numeric values
> context sensitive masking of HTML-output

- themes/default/style.css
- themes/default/style.min.css
interim fix for slipping button bar, see: http://mylittleforum.net/forum/index.php?id=9000
> Fix: button bar slipped below the textarea because of too little space

- includes/login.inc.php
- update/update.sql
- update/update_2.x-2.3.php
The setting variable 'temp_block_ip_after_repeated_failed_logins' has
now a new meaning. A zero means off/not used and a value greater than
zero indicates a timespan.
> login blocking configuration

- update/update_2.x-2.3.php
Fix bug in update function, i.e.:
https://github.com/ilosuna/mylittleforum/issues/21. Update function
takes interim version into account.
> Fix: update function

- index.php
Add correct version number to index.php
> Add correct Version

- js/main.js
Fix for closing issue, cf.
http://mylittleforum.net/forum/index.php?id=8428 The window will not
close, if the scollbar inside the preview element is clicked.
> Fix: closing behavior

- themes/default/style.css
- themes/default/style.min.css
Images with a great width stuck out of the preview block. Now it's shrinked to the elements size.
> Change: set max-width for images in the ajax-preview

- install/index.php
Add bookmark table to install script
> Installscript

- install/index.php
- Add path to favicon of the default template to prevent a 404 error
> prevent 404 error

- includes/index.inc.php
- themes/default/subtemplates/index_table.inc.tpl
- Shows the number of *views of the thread* instead of the number of
*views of the posting* in table view.
> Count number of views of thread in table view

- includes/functions.inc.php
- add modifier u to switch to UTF-8 mode in regexp function in
contains_special_characters to avoid problems with chinese characters,
cf. http://mylittleforum.net/forum/index.php?id=9353
> Pattern Modifier

- update/update_2.3.5-2.4.php
- remove subfolders from update list, if the parent folder is also in
list, cf. http://mylittleforum.net/forum/index.php?id=9359
> Remove Subfolders

- includes/functions.inc.php
- check if array alements exist
> Chech array elements

- update/update_2.3.5-2.4.php
- overwrite the 'db_settings.php' and add new database table 'bookmarks'
- marked changed files with pull-ids
see: https://github.com/ilosuna/mylittleforum/issues/43
> Overwrite db_settings on update

- includes/admin.inc.php
- install/index.php
- lang/english.lang
- lang/german.lang
- themes/default/style.css
- themes/default/style.min.css
- themes/default/subtemplates/admin.inc.tpl
- check for HTML tags
- add slashes
- a warning message is displayed in admin area, if install/index.php still exists
- see: https://github.com/ilosuna/mylittleforum/issues/51
> Fix command execution issue

- install/index.php
- override db_settings_array to fix issue
https://github.com/ilosuna/mylittleforum/issues/60
> Overwrite db_settings array

- update/update_2.3.5-2.4.php
- add lang-directory to update routine v2.4
> consider modified lang files

- includes/admin.inc.php
- includes/functions.inc.php
- install/install.sql
- update/update.sql
- update/update_2.3.5-2.4.php
- remove "read status" on user delete
- remove "read status" on posting delete
--> see https://github.com/ilosuna/mylittleforum/issues/73
> Remove read status of entries on delete

- update/update_2.3.5-2.4.php
- SQL to transfer read state from 'userdata_table' to new table
'read_status_table'
- SQL to remove column 'entries_read' from 'userdata_table'
- see https://github.com/ilosuna/mylittleforum/issues/77
> Transfer read state to new tabel

- includes/functions.inc.php
- install/install.sql
- update/update_2.3.5-2.4.php
- add new parameter to setting_table called 'read_state_expiration_date'
(default 150 days)
- remove read state if 'auto_lock_old_threads' > 0
- remove read state if 'read_state_expiration_date' > 0
- see https://github.com/ilosuna/mylittleforum/pull/75
> Remove read state

- update/update_2.3.5-2.4.php
- remove duplicate item 'auto_lock_old_threads' in setting table
> Remove item

- includes/functions.inc.php
- disable the check for too long words, if param '$word_maxlength' is <=
0
> - too long word check

- includes/functions.inc.php
- adding additional parameter to too_long_word function to specify the
delimiter(s)
> - Add delimiters to too_long_word-Function

- themes/default/subtemplates/admin.inc.tpl
- add CSRF token to admin form
> - CSRF-Token

- includes/avatar.inc.php
- includes/entry.inc.php
- includes/functions.inc.php
- includes/thread.inc.php
- includes/user.inc.php
- a timestamp is added to avatar image file name to avoid caching issues on image replace
- https://github.com/ilosuna/mylittleforum/issues/113
> - Added timestamp to avatar filename

- update/update_2.3.5-2.4.php
- regard number of postings in setting table i.e. 'max_read_items'
- see https://github.com/ilosuna/mylittleforum/issues/77
> - Transfer read state to new table on update

- includes/functions.inc.php
- correcting regexp
- check variable via isset() and file_exists()
> - correcting regexp

- includes/functions.inc.php
- includes/posting.inc.php
- lang/chinese.lang
- lang/english.lang
- lang/german.lang
- Word delimiters added to lang files
- delimiters are used in too_long_word function
- see https://github.com/ilosuna/mylittleforum/issues/105
> - Used word delimiters

- includes/functions.inc.php
- replace avatar function to be compatible to PHP <5.3
> - Replace getAvatar function

- themes/default/subtemplates/admin.inc.tpl
Make the fields for image size a bit wider.
> Change: more space for a few form fields

- includes/functions.inc.php
- limit the number of entries in read_entires-table by 'max_read_items',
if and only if 'max_read_items' > 0
- max_read_items <= 0 means unlimited storage
> - limit the number of entries in read_entires-table

- includes/index.inc.php
- check existence of $total_views to avoid php warning
> - check existence of $total_views

- includes/admin.inc.php
- users can be activated by admins but they are not automated unlocked.
--> Add unlock-condition to activate sql
see: http://mylittleforum.net/forum/index.php?id=9637
> Activate and unlock user by admin

- includes/posting.inc.php
- restrict the if statement by: $settings['dont_reg_edit_by_admin']==1
as well as $settings['dont_reg_edit_by_mod']==1 in last condition
> restrict 'edited by' - output

- includes/posting.inc.php
- check for Null-Value via COALESCE
- https://github.com/ilosuna/mylittleforum/issues/159
> Check for Null-Value

- lang/chinese.lang
- lang/croatian.lang
- lang/english.lang
- lang/french.lang
- lang/german.lang
- lang/italian.lang
- lang/norwegian.lang
- lang/russian.lang
- lang/spanish.lang
- lang/swedish.lang
- lang/tamil.lang
- lang/turkish.lang
Additional preparation for responsive themes that should hide particular informations.
> Change: add spans for hideable interpunction

- update/update_2.3.5-2.4.php
- The files as well as the folders are sorted (by php function sort)
- see https://github.com/ilosuna/mylittleforum/issues/177
> Sorting Update List

- themes/default/style.css
- themes/default/style.min.css
- replace graphic separators with CSS-text (with :before)
- https://github.com/ilosuna/mylittleforum/pull/30
- https://github.com/ilosuna/mylittleforum/issues/193
> replace graphic separator

- includes/functions.inc.php
- replace loop over array items by inbuilt function array_keys
> - simplify get_category_ids

- includes/thread.inc.php
- extend SQL query for 'last_reply' column
- add isset condition
- https://github.com/ilosuna/mylittleforum/issues/195
> Last reply

- themes/default/subtemplates/admin.inc.tpl
I forgot these form fields in [the last attempt](https://github.com/ilosuna/mylittleforum/pull/121).
> Fix: expand further form fields, which was forgotten until now

- includes/index.inc.php
- includes/thread.inc.php
… and a few code style thingamabobs
> distinguish between new and not marked as read also for registered users

- themes/default/main.tpl
- user_type argument is corrected in js_defaults-query
- http://mylittleforum.net/forum/index.php?id=10259
- https://github.com/ilosuna/mylittleforum/issues/247
> Change user_type-argument in js_defaults-query

- includes/entry.inc.php
- Handling of the read state in entry thread by using code from
thread.inc.php
- Could not interpret the former code line 'if($data['pid']==0)'
- see https://github.com/ilosuna/mylittleforum/pull/233
- https://github.com/ilosuna/mylittleforum/issues/245
> Handling of the read state in entry thread

- includes/functions.inc.php
Why ever this didn't came onto my screen …
> Fix: corrected wrong variable name

- update/update_2.3.5-2.4.php
- version number is added to update-array
- https://github.com/ilosuna/mylittleforum/issues/264
> Add version

- themes/default/style.css
- themes/default/style.min.css
Removal of a few obsolete rules as a result of the structure unification of `#sidebar` and `#bottombar`. Additionally e cleanup and a fix for the possible width of the first element in the list of latest postings. It was narrower than the following list elements because of the bottom margin of the toggler of the whole bar.
> A few changes to the CSS-files of the default template

- includes/contact.inc.php
> Cleanup: reformatting of the file contact.inc.php

- includes/account_locked.inc.php
- includes/admin.inc.php
- includes/auto_login.inc.php
- includes/avatar.inc.php
- includes/bookmark.inc.php
- includes/delete_cookie.inc.php
- includes/disabled.inc.php
- includes/insert_flash.inc.php
- includes/js_defaults.inc.php
- includes/login.inc.php
- includes/main.inc.php
- includes/page.inc.php
- includes/posting.inc.php
- includes/register.inc.php
- includes/rss.inc.php
- includes/search.inc.php
- includes/upload_image.inc.php
- includes/user.inc.php
The intendation of the include-files was unified from several different number of spaces to one tab per level. Additionally parenthesis following an `if`, `for`, `while` etc. and functions, equals signs and variables in SQL-queries get separated with a space from the surroundings.
> Refactoring of the PHP-includes

- includes/admin.inc.php
Seems to be a copy 'n' paste error.
> Fix: corrected database query, was broken mix of SELECT and UPDATE

- lang/german.lang
The bug led to the classical output of "Array".
> Fix: removed doubled line with key "smilies_disabled"

- includes/login.inc.php
- index.php
- Redirect user to last visited page after login
- https://github.com/ilosuna/mylittleforum/issues/282
> Redirect after LogIn

- includes/main.inc.php
- themes/default/subtemplates/subnavigation_2.inc.tpl
0 = nested view (threaded view)
1 = linear view (table view)
> Change: fix values for URL-parameter toggle_thread_display

- includes/functions.inc.php
- includes/thread.inc.php
A few fixes for minor issues, catched while studying the code because of issue #288.
> Cleanup: remove unused array, corrected a few spelling errors

- index.php
> Fix: check for existence of the variable and also for it's non-emptyness

- themes/default/subtemplates/admin.inc.tpl
- themes/default/subtemplates/bookmark.inc.tpl
- themes/default/subtemplates/contact.inc.tpl
Removed a doubled closing select-tag, a few empty lines and a size-attribute from an input with type submit that made no sense at all.
> Fix for a few issues in the templates

- includes/bookmark.inc.php
- crorrecting variable in mysqli_free_result
- https://github.com/ilosuna/mylittleforum/issues/334
> Correct variable

- includes/admin.inc.php
- add getAvatar on several placed to handle name convention
- Overwrite https://github.com/ilosuna/mylittleforum/pull/352 because it
is incomplete and due to a conflict in editing this issue
> Avatar handling

- themes/default/main.tpl
- add link to mylittleforum.net
> Change project page link

- lang/english.lang
- lang/german.lang
- add notification of generated message
- https://github.com/ilosuna/mylittleforum/issues/358
> Add email note

- includes/admin.inc.php
Listing of detected errors.
- Fix: use existing variable instead non exisiting one
- Fix: different kinds of check led to unwanted behaviour
> Fix(es) for the uploads management

- includes/functions.inc.php
- due to content changes of github atom feed, the checkUpdate returns
wrong uri
- https://mylittleforum.net/forum/index.php?id=10669
> Check update function

- includes/register.inc.php
- themes/default/main.tpl
Set the meta element for defining the charset as first in the header. If necessary it's value applies now also the title element which wasn't the case before. As second, there was several unnecessary spaces in the `register.inc.php`.
> A small fix and a few cleanups

- includes/posting.inc.php
- includes/register.inc.php
- themes/default/subtemplates/posting.inc.tpl
- themes/default/subtemplates/register.inc.tpl
Several form fields in the registration and the posting forms got randomised names. It's a combination of a fix name (leaned at the fields purpose) combined with the value of the csrf-token, which gets hashed with sha256. Additionally the fields in the registration form got reordered.
> Registration problem in Firefox because of errorneous prefilled input fields

- includes/functions.inc.php
Put the e-mail-address a user can provide to the Reply-to header.
> Fix: always set the forums e-mail-address as sender of an e-mail

- includes/admin.inc.php
- themes/default/subtemplates/admin.inc.tpl
- add token to admin function to avoid cross site request forgery (CSRF)
- see http://owendarlene.com/csrf-my-little-forum/
> CSRF token

- includes/admin.inc.php
- add svg extension in regexp for imgage files
- see https://mylittleforum.net/forum/index.php?id=11050
> SVG support for images

- includes/admin.inc.php
- includes/functions.inc.php
- includes/posting.inc.php
- replaced deprecated function each() by its foreach representation
- see https://github.com/ilosuna/mylittleforum/issues/409
> Remove deprecated function each()

- includes/admin.inc.php
- includes/functions.inc.php
- includes/posting.inc.php
Remove occurences of `email_notification` from several places, repair saving of subscription during posting edit.
> Fix: subscritions bug that was solved only for legacy branch before

- includes/bookmark.inc.php
- check sql result for NULL value
> Check NULL value

- lang/french.lang
All remaining strings should now be translated.
> Update FR translation

- includes/contact.inc.php
- includes/posting.inc.php
- includes/register.inc.php
- correcting condition for checking max. receipt_time
- https://github.com/ilosuna/mylittleforum/pull/413
> max. receipt time

- includes/user.inc.php
- lang/chinese.lang
- lang/croatian.lang
- lang/danish.lang
- lang/english.lang
- lang/french.lang
- lang/german.lang
- lang/italian.lang
- lang/norwegian.lang
- lang/russian.lang
- lang/spanish.lang
- lang/swedish.lang
- lang/tamil.lang
- lang/turkish.lang
- themes/default/subtemplates/user_edit_pw.inc.tpl
- removed field to confirm changed password in user area
- see: https://github.com/ilosuna/mylittleforum/pull/412, https://github.com/ilosuna/mylittleforum/pull/403
> Change user password

- includes/register.inc.php
- includes/user.inc.php
- added unicode character properties to reg. exp
> Unicode character properties

- includes/functions.inc.php
Delete them too to clean up the subscriptions table.
> Fix: deleting a posting could leave orphaned subscriptions

- includes/admin.inc.php
- includes/functions.inc.php
- install/index.php
- install/install.sql
- themes/default/subtemplates/admin.inc.tpl
As I want to rebuild the settings form, I came across a few settings, that are marked as automatisms that **must stay untouched** when changing the settings. because of that I moved them to the table `mlf2_temp_infos`. Noone will touch them there with exception of the scripts.
The only remaining tasks are the admin script when building the settings page and the installation and update scripts (thatswhy it is marked as WiP).
> Tempsettings

- config/db_settings.php
- includes/upload_image.inc.php
- install/index.php
- install/install.sql
Until now an uploaded image is not certainly attibutable to a user. In the best case an image is in use in an entry so one can assume, that the author of the entry is also the uploader.
To simplify the handling of uploaded images we want to store the informations about the uploader and the time of the upload in a new database table.
This is work in progress and not ready yet.
> Store information about uploads in a database table

- includes/upload_image.inc.php
… hardcoded table name, clapper board, fourteenth …
> Fix: no hardcoded table names, dammit!

- includes/admin.inc.php
- install/index.php
- install/install.sql
Fixes have to be adapted to the master in preparation for version 2.5.
> Bugfixes from the work on version 2.4.19

- themes/default/style.min.css
The CSS was tested in style.css but the changes got not adopted to the minimised CSS file.
> Fix: CSS-changes for PR #364 wasn't taken over to the file style.min.css

- includes/functions.inc.php
- removed get_mail_encoding function
- set charset to defined value in i18n file
- reformatted my_mail function
- see https://mylittleforum.net/forum/index.php?id=11715
> Mail encoding

- includes/rss.inc.php
Code was provided by Mardor (Martin Vogel, https://bauforum.wirklichewelt.de/) and enhanced with htmlspecialchars.
> Fix: correct the path to images to an absolute URL in the RSS feed

- themes/default/style.css
- themes/default/style.min.css
> Change: style the new button for quote inserting like the link it was before

- themes/default/subtemplates/admin.inc.tpl
flash-bbcode has been removed in 2.5, so this checkbox is obsolete
the other changed lines harmonized the line endings
> remove checkbox for flash

- themes/default/subtemplates/contact.inc.tpl
- removed smarty code, which was added for debugging in https://github.com/ilosuna/mylittleforum/pull/489
> Remove smarty code

- includes/posting.inc.php
- update/update_2.4.19.1-2.5.php
If the posting is classified as SPAM, redirect the user to the single entry view, which contains the SPAM warning message, see https://github.com/ilosuna/mylittleforum/issues/464
> SPAM warning message

- config/b8_config.php
- includes/contact.inc.php
- includes/posting.inc.php
- index.php
- created config file for B8
- see https://github.com/ilosuna/mylittleforum/issues/492
> B8 config file

- includes/main.inc.php
- correcting SQL statement to display threads, that contains at least one spam posting
- https://github.com/ilosuna/mylittleforum/issues/473
- https://github.com/ilosuna/mylittleforum/pull/488
> SQL stmt to show SPAM threads

- includes/posting.inc.php
- flag postings of admin/mod always as HAM (use it also to train the filter)
> Handle mod/admin posting by B8 as HAM

- includes/posting.inc.php
- to avoid redundantly trainning data on edit a posting, the decision of the original posting is removed from trainning DB
> B8 unlearn on edit posting

- includes/functions.inc.php
- clearing all recipients of PHPMailer
> clear recipients

- install/install.sql
- update/update_2.4.19.1-2.5.php
- Update install and update script for PHPMailer configuration
- https://github.com/ilosuna/mylittleforum/pull/499, https://github.com/ilosuna/mylittleforum/pull/498
> Update install and update script

- config/b8_config.php
- config/php_mailer.php
- includes/b8.inc.php
- includes/contact.inc.php
- includes/mailer.inc.php
- includes/posting.inc.php
- index.php
- since PHP 5 doesn't support arrays in define(), the config files are invalid, see https://mylittleforum.net/forum/index.php?id=11912
- removed define() function call and used _normal_ arrays syntax
- created a single instance of B8 instead of using multiple instances (added new include file)
> Replace definition of constant array by normal array

- includes/entry.inc.php
- excluded stored and classified SPAM entries in thread tree (below the entry)
- see https://mylittleforum.net/forum/index.php?id=11936
> SPAM in tree

- includes/main.inc.php
- if one (an admin/mod) deletes the listed spam entries, one is NOT redirected to the normal view
- the spam counter (`$total_spam`) is used as a further condition
> display spam

- includes/functions.inc.php
See therefore [this thread in the project forum](https://mylittleforum.net/forum/index.php?id=11999) (german language).
> Change: natural, case insensitive sorting for main pages tag list

- includes/functions.inc.php
- added bb-code tags [RTL] and [LTR]
- reformatted functions
- see https://mylittleforum.net/forum/index.php?id=12148
> RTL / LTR - tags

- includes/posting.inc.php
- check, if an entry that is classified as SPAM by B8 should stored to the DB (or not)
> Fix: store SPAM entry option was not used

- includes/functions.inc.php
- includes/posting.inc.php
Problem: if SPAM is deleted automatically by `daily_actions`, dependent tables were not updated 
Solution: Existing function `delete_posting_recursive` is used to delete SPAM entries
> Auto delete spam

- themes/default/style.css
- themes/default/style.min.css
- added padding to to the link to the rss-feed of the thread (in thread view)
- padding was removed during re-organisation of the footer, cf. #531, #533, but the link is not part of the footer
- see https://mylittleforum.net/forum/index.php?id=12336
> CSS for RSS of the Thread (Thread View)

- themes/default/style.css
I forgot to remove it in #537.
> Fix: delete hyperfluous comma

- js/admin.js
- js/main.js
- js/posting.js
- remove out-dated sources
- translate comments of functions
- https://mylittleforum.net/forum/index.php?id=12389
> Clean script files

- js/admin.js
- js/main.js
- js/posting.js
- use DOMContentLoaded to init scrips on (DOM) load
> DOMContentLoaded

- includes/user.inc.php
- Postings classified as SPAM are accessible via user-area
- A modified SQL stmt restricts the postings list and filters SPAM postings for normal users
- cf. https://mylittleforum.net/forum/index.php?id=12422
> SPAM postings of a user

- modules/phpmailer/Exception.php
- modules/phpmailer/OAuth.php
- modules/phpmailer/PHPMailer.php
- modules/phpmailer/POP3.php
- modules/phpmailer/SMTP.php
> Module update

- modules/bad-behavior/bad-behavior-generic.php
- modules/bad-behavior/bad-behavior/banned.inc.php
- modules/bad-behavior/bad-behavior/blacklist.inc.php
- modules/bad-behavior/bad-behavior/cloudflare.inc.php
- modules/bad-behavior/bad-behavior/common_tests.inc.php
- modules/bad-behavior/bad-behavior/core.inc.php
- modules/bad-behavior/bad-behavior/post.inc.php
- modules/bad-behavior/bad-behavior/roundtripdns.inc.php
- modules/bad-behavior/bad-behavior/searchengine.inc.php
- modules/bad-behavior/bad-behavior/whitelist.inc.php
- comment symbol '#' is replaced by '//' because a new version is NOT available
- there are a lot of "FIXME"; is it realy a trustworthy module?!
> Comments (PHP8)

- includes/admin.inc.php
- Language part for `emails` was not loaded to the user
- ConfigLoad is added, cf. https://github.com/ilosuna/mylittleforum/issues/564
> Activation mail

- includes/functions.inc.php
- delete inactive users that are *not* locked by the form admin
> user lock state

- js/main.js
- changed array name back to avoid confusion
> Array name

- modules/geshi/geshi.php
- create_function has been removed in PHP 8
- replaced by anonymous function
> create_function (PHP 8)

- includes/mailer.inc.php
- modules/phpmailer/OAuth.php
- modules/phpmailer/OAuthTokenProvider.php
- modules/phpmailer/PHPMailer.php
- modules/phpmailer/POP3.php
- modules/phpmailer/SMTP.php
> PHPMailer v6.6.0

- includes/entry.inc.php
- Automatic conversion of false to array is deprecated in PHP 8
> Automatic conversion

- themes/default/main.tpl
This is no acute attempt of a rework of the old default theme but only a change of the doctype from XHTML 1.0 to HTML (5).
> Use modern HTML doctype

- includes/functions.inc.php
- check if database name is passed
> Check database

- includes/admin.inc.php
- includes/auto_login.inc.php
- includes/contact.inc.php
- includes/functions.inc.php
- includes/login.inc.php
- includes/main.inc.php
- includes/posting.inc.php
- includes/register.inc.php
- includes/search.inc.php
- includes/user.inc.php
- install/index.php
- update/update_2.4.19.1-2.5.php
Solved it with checks for non empty strings before trimming and a second check, if the string is empty after trimming.
> Prevent providing NULL values for functions trim, ltrim and rtrim because it's deprecated with PHP 8.1

- includes/functions.inc.php
- includes/user.inc.php
> Remove a function call of strftime that leftover #587

- lang/croatian.lang
- lang/english.lang
- lang/italian.lang
- lang/spanish.lang
- lang/tamil.lang
- lang/turkish.lang
German: "aktuell" to wrong English "actual", correct is "currently"
This one triggered me again and again. Now I didn't forget to fix it. :-)
> Corrected a false friend in translation

- includes/functions.inc.php
- Number of notification mails restricted to 25
- Condition removed that checked the return value of my_mail
> Restrict number of mails

- themes/default/style.css
- themes/default/style.min.css
There are several CSS-rules, which repeats existing rules. I found a few of these and simplified the CSS-code a bit.
> Harvesting a few low hanging fruits

- update/update_2.4.19.1-2.5.php
There was a syntax error in the update script (`%connid` versus `$connid`).
> Fix: correct syntax error

- themes/default/style.css
- themes/default/style.min.css
This is a little UI enhancement. It makes buttons more recognisable as with the background colour change and the borders alone.
> Change cursor to pointer when hovering buttons

- includes/posting.inc.php
- themes/default/subtemplates/posting_flag_ham.inc.tpl
- themes/default/subtemplates/posting_report_spam.inc.tpl
- Date format corrected in template for reporting SPAM/HAM
> Date format

- includes/user.inc.php
- themes/default/subtemplates/user_profile.inc.tpl
- formated date corrected in user profile
> Formated date

- README.md
This is a base for the discussion about what features should be featured in the readme.
See therefore also the issue #661
> Add a featurelist to the readme file

- update/update_2.4.19.1-2.5.php
The update process is failing. I fixed some issues.
> fixed missing double point

- modules/captcha/captcha_image.php
I forgot to remove it in #668, this fixes #688
> Being not verbose to visitors with error reporting

- index.php
- modules/captcha/captcha_image.php
- added SameSite attribute in session cookie as discussed by Auge #696
> SameSite attribute in session cookie

- includes/auto_login.inc.php
- includes/delete_cookie.inc.php
- includes/functions.inc.php
- includes/login.inc.php
- includes/main.inc.php
- includes/posting.inc.php
- includes/user.inc.php
- modules/smarty/sysplugins/smarty_internal_debug.php
- SameSite attribute added in setcookie function, cf. #696
> SameSite attribute in setcookie function

- includes/functions.inc.php
Implement the codestyle in all functions and refactor a few functions for better readability.
> Reformatting and refactoring of the functions in functions.inc.php

- includes/search.inc.php
- user name of _registered_ users added to query
- #716
- code redundancy reduced
> Include user name

- includes/search.inc.php
> Clean code

- includes/thread.inc.php
- themes/default/style.min.css
- fix a typo in a code comment
- remove unnecessary spaces and semicolons in `style.min.css`
> Apply two small fixes for bugs I found along the way

- README.md
- includes/admin.inc.php
- includes/functions.inc.php
- lang/arabic.lang
- themes/default/subtemplates/admin.inc.tpl
- update/update_2.4.19-2.5.php
- correcting URLs to the project repository
- mark Bad Behavior as removed in the Readme
- rename the language name "arabian" to "arabic"
- clarify the instruction to remove outdated files and directories
> Latest preparation for releasing the version 20240729.1

- includes/posting.inc.php
- exclude the check for existing usernames when the admin/mod edits the post
- https://github.com/My-Little-Forum/mylittleforum/issues/750
> Existing username

- themes/default/style.css
- themes/default/style.min.css
While the changes of the HTML-sources for modern form field types was applied to the PR #754, I forgot to add the few necessary changes of the CSS.
> Add the forgotten CSS-rules for PR #754

- includes/index.inc.php
- Change scope of ‘$pid_result_sql’ statement to be available in conditions
> Scope of statement

- includes/index.inc.php
- redundant code parts reduced
- #763, #764
> Code cleaning

- includes/upload_image.inc.php
- WEBP file extension added, cf. #766
> File filter

- includes/avatar.inc.php
- themes/default/avatar.tpl
This was done to make the appearance of the popups to upload avatars and to upload images for the use in postings similar. Use a similar HTML-structure, identical CSS-rules (only the needed rules) and adapted but at least similar JavaScript code.
> Rework of the avatar template

- themes/default/avatar.tpl
Herewith I deliver changes that I had forgotten in #774.
> Small fixes for forgotten changes in the avatar template

- themes/default/style.css
The changes improve the readability of the code in the file `style.css`. Each selector and each property is noted on a separate line. A space is noted between the property name including the colon and the value.
This is a purely reformatting of the code *without any functional change*.
> Reformatting the code in the file style.css

- includes/user.inc.php
Reverts My-Little-Forum/mylittleforum#783
> Revert "Access"

- includes/user.inc.php
- depending on the forum settings, access to the user area is restricted
- https://mylittleforum.net/forum/index.php?id=18808
- (more) corrected version of #783
> Access v2.0

- themes/default/subtemplates/admin.inc.tpl
The value of the checkbox has to be the filename/path of the image, not the counter for the list.
> Fix the value of the upload managment checkbox

- includes/index.inc.php
- Depending on the user type, the view of the thread list is restricted, #794
> Permission

- themes/default/style.css
- themes/default/style.min.css
Deleted unnecessary code fragments and added the changes in style.min.css also to style.css.
> A few small CSS fixes

- themes/default/images/general-lock-closed.svg
- themes/default/images/general-lock-open.svg
- themes/default/images/tick.svg
- themes/default/style.css
- themes/default/style.min.css
Added a few fixes for graphics I forgot to include in previous commits. Furthermore I removed a few remainings in the code of previously reworked things. There could be more fixes to come.
> A collection of fixes in context of the SVG icons

- includes/functions.inc.php
- Unnecessary attributes removed, cf. https://mylittleforum.net/forum/index.php?id=18990
- Alternative text added
> Attributes

- includes/user.inc.php
… and count its elements for checking if its empty or not. This is a followup of #846.
> Initialise array $last_posting as array
