install/index.php

The script can't use the connection identifier to report it's absence. Use the correct function for this case.
It's only a corner case but a common one. It could often occure, that users speciffy incorrect informations about the database connection. And in my case it did when I specified the server name with a typing error.

Fix: error in the cornercase of connecting the database server

---

modules/stringparser_bbcode/stringparser.class.php
modules/stringparser_bbcode/stringparser_bbcode.class.php

- Add __construct-Function to classes to be valid for PHP7
- Check length of content-string @matchesCriterium-function to avoid a
PHP note

Constructor for PHP7

---

includes/user.inc.php

Reinsert the variable $user_name. The context sensitive handling of it's content stays beside the handover to Smarty. This is because of the clear view in case of a maintenance necessity. fixes #28

Fix: missing user name in users entries list

---

themes/default/style.css
themes/default/style.min.css

A detail, that annoys me every time I visit the project forum is a bit of a background image, I see on the left bottom corner of the usermenu links. I replaced the CSS-background image with a pipe, inserted with `#usermenu li:before`.
The upper part is a screenshot from the project forum, the lower one with the fix is a screenshot from my test installation.

Fix: replace graphic separators with CSS-text (with :before)

---

includes/entry.inc.php
includes/functions.inc.php
includes/thread.inc.php

The read status will be written to the table `mlf2_read_status` on every request for an entry (`includes/entry.inc.php` and `includes/thread.inc.php`).

save read status to table

---

includes/auto_login.inc.php
includes/login.inc.php

Setting `temp_block_ip_after_repeated_failed_logins` define the time limit,
if the value is greater than 0. That has to be respected, when the check should be triggered.

Fix: trigger login control with all setting values > 0

---

install/install.sql
update/update_2.3.5-2.4.php

Alternatively, more general attempt for a solution of #99. See also PR #112 
The datasets from the settings table will be transferred into an array. Keys with identic names will overwrite each other, so it ends with onle line per setting. After altering the table structure (PK and table type), the settings will be written back into the table.
Any thoughts?

Change: alter settings table and rewrite the settings

---

includes/index.inc.php
includes/thread.inc.php

An entry is either new or read but it can't be both.
Use the new read status for registered users and the old
cookie based behaviour for not registered visitors.

Fix: a new entry can't be read and a read one can't be new

---

install/index.php

The construct break breaks in an if-block. Use the dirty `die()` instead.

Fix: use dirty die instead wrong break

---

includes/admin.inc.php
includes/functions.inc.php
themes/default/subtemplates/admin.inc.tpl

- Download/info uri is extracted from ATOM using LINK-element
- RegEx to get the version is updated to match both: '1.2.3' and 'v1.2.3'
- URI is stored in 'temp_infos_table' as 'last_version_uri'
- see: https://github.com/ilosuna/mylittleforum/issues/155

Extract Download-URI from ATOM-Feed

---

themes/default/subtemplates/posting.inc.tpl

- a hidden field is added, if select is disabled to transfer the category-value
- https://github.com/ilosuna/mylittleforum/issues/166

Add hidden field for category

---

includes/functions.inc.php

- PHP object is initialized by an array-type to be valid with PHP 5.2 and 5.3.
- see https://github.com/ilosuna/mylittleforum/issues/169
- see http://mylittleforum.net/forum/index.php?id=9828

PHP-Object problem

---

includes/functions.inc.php
install/index.php

It's for convenience of the potential forum admins that want's to install MLF and run it HTTPS-based.

pre-populate the field for forum-URL with the correct protocol string

---

includes/functions.inc.php

Top level domains with more than 4 chars are present since far more than ten years ([.museum](https://en.wikipedia.org/wiki/.museum) started back in 2001). So either the regular expression has to altered or the PHP-function `filter_var`, which is much more generic, has to be used.
After reading the user contributed notes in the PHP documentation page for [the function filter_var](https://secure.php.net/filter_var) I decided against `filter_var` and to alter the regular expression instead. The use of `filter_var` for e-mail-validation can cause false negatives because the function can't handle puny-code domain-names (domain names with non latin chars). That's a no go nowadays (IMHO).
The regular expression allows now TLDs with *two **or more** chars*.

Fix: allow e-mail-addresses with TLDs longer than 4 chars

---

update/update_2.3.5-2.4.php

If the error message tells you, that the installed and new version share the same version number, it is possible, that you forgot to upload the file `config/VERSION`. The error message now includes this information.

Fix: mention the check for the actual version of config/VERSION

---

includes/entry.inc.php
includes/functions.inc.php
includes/index.inc.php
includes/thread.inc.php

As a last step for the unification of the handling of the messages read- and new-status I implemented the proposal of @derletztekick from the discussion in the PR #251 thread. In my testing forum (with only three accounts) it seems to work without side effects *at first sight*. It might be a good idea to test it in a regulary forum.
With the function we'll have a unified behavior and in case of changes only one place to edit. I like your solution @derletztekick. Please take a look before merging the code. :-)

Outsourcing of read- and new-status handling into a function

---

themes/default/main.tpl

It's a small step for the privacy of the visitors of a forum. If users follows links to external sites, no referrer will be sent. Browsers, that implemented only the old draft, a shortened referrer with the requesting domain name will be sent.
1st meta element: old draft, see https://wiki.whatwg.org/wiki/Meta_referrer (for Edge, Safari)
2nd meta element: actual draft, see https://w3c.github.io/webappsec-referrer-policy/

Small privacy enhancement, don't send always a referrer

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/index.inc.tpl
themes/default/subtemplates/index_table.inc.tpl

To make it easier to share the CSS-rulesets for the list of latest postings for registered and unregistered users, the class `read` was tied to the link itself instead to the `span` that contains the subject of the entry. On that way links with the class `read` and with the pseudo class `:visited` can share the same rules. Before this was impossible because of class `read` was tied to a span within the link.
Additionally the blocks in `#bottombar` got the same ids as the corresponding blocks in `#sidebar`. To achieve this, a few rules was re-tied to parent elements and corrections ws made.

Rework of the HTML-structure for the list of latest postings

---

includes/admin.inc.php

- change not defined $lang['error_input_too_long'] to
$lang['error_username_too_long']

correct label

---

includes/functions.inc.php

Both bugs broke different parts of the backup function.

Bugfixes for invalid backup-mode-check and disused table column mlf2_entries.tags

---

update/update_2.3.5-2.4.php

This is important for updates from older versions as long as the CSS-files will not get actualisations during future updates.

Fix: corrected the path to the CSS-files in the file list for version 2.4.7

---

includes/functions.inc.php

This prevents jumping of the content of a page because of unknown image size in some cases. It only takes effect for uploaded images in the default directory `images/uploaded`. Images that are included from other sources are not affected at all. Latter images will make the page jump during loading process as before.
See also issue #356.

Add width and height attributes to img tag of uploaded images

---

themes/default/subtemplates/user_agreement.inc.tpl

Simple but annoying copy'n'paste error.

Fix: correct wrong settings-key for the terms of use URL

---

lang/turkish.lang

Workaround was to use US-locales instead the turkish ones for a PHP-bug that was solved ages ago with PHP 5.2. See also #361.

Change: removed the workaround for turkish language

---

includes/contact.inc.php
includes/functions.inc.php
includes/posting.inc.php
includes/register.inc.php
install/install.sql
update/update.sql
update/update_2.4.8-2.5.php

- observe timespan for form completion and show an error, if the timespan is below a suitable threshold
- remove hard coded thresholds
- add new database entries for tuning threshold values
- default values: min = 5 sec and max = 10800 sec
- remove "credit time" for incomplete filled forms
- no distinction of user type
- see https://github.com/ilosuna/mylittleforum/issues/406

Timespan for form completion

---

index.php

- added `setlocale(LC_NUMERIC, "C");` to handle the decimal separator (in case of content switching)
- https://github.com/ilosuna/mylittleforum/issues/428

LC_NUMERIC

---

themes/default/style.css
themes/default/style.min.css

With `height: auto;` for `img.thumbnail` the height is set by the browser to the value that respects the image ratio in relation to the given width of (currently) `150px`.

Fix: thumbnails was elongated to the complete height of the entry

---

includes/posting.inc.php

I've no clue, why I used `UPDATE foo = foo AND bar = bar` instead the correct `UPDATE foo = foo, bar = bar`.

Fix: wrong syntax for UPDATE, used AND instead the correct comma

---

includes/admin.inc.php
includes/functions.inc.php

- Use of `mysqli_fetch_all` is not safe because some PHP installations doesn't know this function. Use `mysqli_fetch_assoc` in a loop instead.
- When fetching only one line of a database request (`SELECT`), `mysqli_fetch_assoc` returns a flat array (`$foo` instead `$foo[0]` for the first row)

Bugfixes for version 2.4.19

---

includes/posting.inc.php

- check for spam and send notification, if entry was wrongly flagged as spam
- DO NOT send mail, if entry is used for training ham messages (but was not flagged as spam)

Notification mails

---

install/install.sql

When fixing the collation for `mlf2_b8_wordlist`, we also need to change the storage engine of this table.
UTF-8 is a variable encoding, having 1 to 4 bytes encoding a single character. Assuming that every character of the `token` field is a 4 byte char, the primary key would be larger than 1000 bytes which is the maximum key length for MyISAM tables.
closes #482

fix collation of wordlist table

---

update/update_2.4.19.1-2.5.php

- added else statement to generate an error if config file is located elsewhere

Missing worst case scenario

---

includes/admin.inc.php
themes/default/subtemplates/admin.inc.tpl

- corrected error message if the length of the user name is invalid
- corrected setting variable used in if-condition that checks the length (`$settings['username_maxlength']` instead of `$settings['name_maxlength']`, which is used for the real name of the user)

new users (created by admin)

---

includes/functions.inc.php

- corrected SQL for auto delete spam
- spam is deleted if at least one service classified an entry as spam

auto delete spam

---

includes/user.inc.php

- it was impossible for an user to change its own(!) settings or to show its own(!) posting list, if `$settings['user_area_access']` was restricted to mods and admins
- corrected/moved condition to the _right_ place to enable access to user area (if enabled) and to allow for editing user settings

access to user area

---

includes/user.inc.php

- the complete code for deleting the account was moved to a function, see function.inc.php::deleteUser, thus, this _new_ function is called here, too, to avoid redundancy

remove account

---

themes/default/main.tpl
themes/default/style.css
themes/default/style.min.css

With the back-to-top-link, introduced in #530, I added an invalid HTML structure for the link, provided in the page footer. Additionally the link was be shown only, when RSS is activated.
Now the link in the footer shows up in every case on every site. The links, inserted in the options lists, connected to every entry, was not affected by the bug.

Fix for invalid HTML structure introduced in #530

---

themes/default/style.css
themes/default/style.min.css

- added padding to to the link to the rss-feed of the thread (in entry view)
- padding was removed during re-organisation of the footer, cf. https://github.com/ilosuna/mylittleforum/pull/531, but the link is not part of the footer

CSS for RSS of the Thread

---

includes/entry.inc.php
themes/default/subtemplates/entry.inc.tpl

Add the information and classes to the user name elements to make them behave like thread trees in the main views. That makes styling of the user names working in every occurence of displaying a thread tree.
Fixes #535

Add field user_type to the thread tree below a single entry

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/thread.inc.tpl
themes/default/subtemplates/thread_linear.inc.tpl

With the changes from #530, followed by fixes in #531 and #533 we encountered a few issues with RSS links in different views of entries and threads. After a research of the forum operator WorldofBB, documented in [this forum entry](https://mylittleforum.net/forum/index.php?id=12336), Micha added the proposed fix in #534. This pull request enhances the solution by unifying the HTML-structure in all three views to the one of the single-entry-view.
It was necessary to add an additional `div` to reflect the structure in the header above the thread tree of the single-entry-view even it has no function in the whole-thread-views. It should make the CSS a bit more maintainable. I would like it to remove the `div` again but in the single-entry-view it is needed and because of that it would come …

Unify HTML-structure for RSS links in the entry views

---

themes/default/subtemplates/entry.inc.tpl

This change adds the missing HTML-elements of the structure in the threaded views to the single entry view. Only exception is the id on div.wrapper that seems to make no sense to me in the context of the single entry view.

Same structure as in the threaded views for the single-entry-view

---

themes/default/main.tpl

After discussing the failed attempt to add the possibility of activating the attribute target in links in entries (#540), we want to implement it in another way. The only one commit from the failed PR, that we can reuse, is the mandatiory change of the HTML dialect from XHTML 1 strict to XHTML 1 transitional.

Change: alter the doctype, change from XHTML 1.0 strict to transitional

---

includes/main.inc.php

- `get_magic_quotes_gpc` is removed because this function returns always `false`
- `get_magic_quotes_gpc` is deprecated cf. https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
- see also https://github.com/ilosuna/mylittleforum/issues/552

get_magic_quotes_gpc

---

includes/avatar.inc.php
includes/classes/Backup.class.php
includes/functions.inc.php
includes/index.inc.php
includes/login.inc.php
includes/posting.inc.php
includes/thread.inc.php
includes/upload_image.inc.php

- in PHP 8, # is no longer interpreted as the start of a comment, as this syntax is now used for attributes, cf. https://www.php.net/manual/en/migration80.incompatible.php, #552 
- comments are removed, if they are identified as /obsolete fragments/, i.e., former code/debugging code
- comment symbol '#' is replaced by '//'

PHP 8: Comment symbol

---

modules/stringparser_bbcode/stringparser.class.php
modules/stringparser_bbcode/stringparser_bbcode.class.php

- Array and string offset access syntax with curly braces is deprecated in PHP 7.4
- Array and string offset access syntax with curly braces is removed in PHP 8
- replaced {} - braces by [] - braces

curly braces

---

includes/bookmark.inc.php
includes/search.inc.php

- Function create_function() is deprecated in PHP 7, cf. https://www.php.net/manual/en/function.create-function
- Closure is used to handle anonymous functions in preg_replace_callback

create_function PHP 7.4

---

js/main.js

add target attribute to links in entries depending on the user preferences
work in progress

Link target

---

modules/smarty/plugins/shared.mb_str_replace.php

- PHP 8.1 PHP Deprecated: implode(): Passing null to parameter #1 ($string) of type string is deprecated
- checked first parameter

Passing null

---

includes/functions.inc.php

The condition defines the number of users, that are selected for sending the inactivity messages during one run of the daily actions. Unlimited sending of e-mails can lead to a temporary grey- or blacklisting of the forum domain. Restricting the number of users and e-mails makes it less probable to get grey- or blacklisted.

Stronger restriction of the number of inactivity messages

---

themes/default/main.tpl
themes/default/style.css
themes/default/style.min.css

Because of the recent changes (doctype from XHTML 1.0 to HTML (5)) a bug appeared. It caused the user menu to disappeared in some cases because of the fixed height of the header. The menu slips out of the visible area and is unreachable on narrow viewports.
I reworked the header with using a media query that makes it possible to put the elements one below the other on narrow viewports and to put it side by side on wider viewports. So there is no big difference on great screens with a large browser viewport. On narrow viewports, where the bug appears, the elements are stapled vertically with no limit of the headers height. So the elements are visible all time. 
See also #607

Rework of the page header

---

includes/functions.inc.php

If the account of a user gets deleted, we can assume, that the user doesn't want to get further notifications about replies to the own forum entries.
This fixes #610

Remove notification about replies in case of deleting a user account

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/entry.inc.tpl
themes/default/subtemplates/posting.inc.tpl
themes/default/subtemplates/thread.inc.tpl
themes/default/subtemplates/thread_linear.inc.tpl

When inserting floated images into an entry, the signature, which was a part of the entry's HTML-container until now, floated with the entries own content around the image when the content was not enough to float around the image itself. The current change puts the signature into a separate container, that *follwos* the entries container and defines a floating context for the entry container.
That way the signature will be displayed below the complete entry in every case.

Ensure the position of the signature below all entry content

---

includes/search.inc.php

The array `$search_string_array` is not initialised, iff the search box is left empty and cased an error/warning, cf. https://mylittleforum.net/forum/index.php?id=13112

Empty search box

---

includes/admin.inc.php
includes/functions.inc.php
includes/upload_image.inc.php

Because of [a request in the project forum](https://mylittleforum.net/forum/index.php?id=13145) I researched the conditions for supporting WebP-images in the image-upload-feature. It was a sitting duck to adapt the existing code because creation a WebP-image works similar to the equivalent functions for GIF-, JPEG- or PNG-images. Furthermore I changed the file type detection for images because using `getimagesize` for this purpose [is not recommeded anymore](https://www.php.net/manual/en/function.getimagesize.php).
> "Do not use `getimagesize()` to check that a given file is a valid image. Use a purpose-built solution such as the [Fileinfo](https://www.php.net/manual/en/book.fileinfo.php) extension instead."
The file-type-check is now based on the MIME-type. As a side effect of this …

WebP support for image upload

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/posting_flag_ham.inc.tpl
themes/default/subtemplates/posting_report_spam.inc.tpl

The buttons are styled inline and have no gaps inbetween. They have therefore a poor usability especially on mobile devices with small viewports. The flexbox brings customisable gaps to them. Furthermore I changed the submit buttons from `input` of type submit to `button`. That way we have more control over the content of the buttons ((styled) text, icons, …) 
To change to `button` and to classifying their parent element as `.buttonbar` makes it easy to reuse the rules for other cases. Make the buttons buttons and put the buttons into an element with the class `.buttonbar` and you are done.

flexbof for ham and spam buttons, ready for reuse

---

themes/default/style.css
themes/default/style.min.css

Before the current solution with a flexbox the user menu list was defined as `display: inline;` with the addition of `text-align: right`. Now it is a flexbox and so it is necessary to put the flex items to the end of the flexbox to get the same look as before (right aligned items).

Put the links in the usermenu to the (right) end of the box

---

README.md

This is a manual how to upgrade an existing forum installation to a newer version. It follows [a request in the project forum](https://mylittleforum.net/forum/index.php?id=12235).
Furthermore there was two minor issues in the readme, that I solved aside the main task.

Add an upgrade manual to the readme

---

themes/default/subtemplates/admin.inc.tpl
themes/default/subtemplates/login.inc.tpl
themes/default/subtemplates/register.inc.tpl
themes/default/subtemplates/user_edit_email.inc.tpl
themes/default/subtemplates/user_edit_pw.inc.tpl
themes/default/subtemplates/user_remove_account.inc.tpl

This is necessary in browsers which sends content of an input field with type text to external spell checking services, as Chrome does with sending the content to a Google service.
We implemented the function to display an password in its input of type *password* with changing the type to *text* with JavaScript. In this moment the content of the input field is simply text that can be handled by the browsers internal spell checking function. If a browser sends the input content to an external service, as Chrome does, a password will be immediately exposed to this external service. Even it is not marked as a password in this moment, it is undesirable to expose passwords to any external entity at all.
fixes #644

Prevent passwords from spell checking for the case of displaying them with type="text"

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/admin.inc.tpl
themes/default/subtemplates/bookmark.inc.tpl
themes/default/subtemplates/contact.inc.tpl
themes/default/subtemplates/entry.inc.tpl
themes/default/subtemplates/errors.inc.tpl
themes/default/subtemplates/login.inc.tpl
themes/default/subtemplates/page.inc.tpl
themes/default/subtemplates/posting.inc.tpl
themes/default/subtemplates/posting_delete.inc.tpl
themes/default/subtemplates/posting_delete_marked.inc.tpl
themes/default/subtemplates/posting_delete_spam.inc.tpl
themes/default/subtemplates/posting_flag_ham.inc.tpl
themes/default/subtemplates/posting_manage_postings.inc.tpl
themes/default/subtemplates/posting_move.inc.tpl
themes/default/subtemplates/posting_report_spam.inc.tpl
themes/default/subtemplates/posting_unsubscribe.inc.tpl
themes/default/subtemplates/register.inc.tpl
themes/default/subtemplates/user_edit.inc.tpl
themes/default/subtemplates/user_edit_email.inc.tpl
themes/default/subtemplates/user_edit_pw.inc.tpl
themes/default/subtemplates/user_profile.inc.tpl
themes/default/subtemplates/user_remove_account.inc.tpl

Until now there are three classes of system messages (`.ok`, `.caution`, `spam-note`) for paragraphs with system messages. Additionally the code contains the reuse of the class `.caution` (in example in the user settings for warning about account deleting) and the class `.spam` for marking the subject of an entry, that is classified as spam and with roughly the same rules as `.spam-note`.
With the introduction of an additional class for all the system messages, called `.notice`, we can distinct the system messages from the reuse of class `.caution`. We can handle the spam classes in the similar way by renaming the class `.spam-note` to `.spam` and by the distinction of subjects of class `.spam` from system messages by using `.notice.spam`. That way it is also possible to outsource some of …

Change HTML and CSS for system messages

---

includes/functions.inc.php

This adds the attribute `loading` with the value `lazy` to all images in forum entries. Images in the browser viewport will be loaded immediately and outside the viewport at the time, the browser detects that they are about to enter the viewport. Browsers, that doesn't support the attribute will ignore it and will load the images as without the attribute (so as before).
closes #666

Change: add lazy loading attribute to img elements in forum entries

---

modules/captcha/captcha.php
modules/captcha/captcha_image.php

As [reported in the project forum](https://mylittleforum.net/forum/index.php?id=14994) and documented in issue #658 it is possible, that the function `imagerotate` does not work with the rotation angle of exactly 180° *in **very** rare cases*. Leaving aside the fact that the concept of captchas is absolutely out of date and thinking about the current solution in `modules/captcha/captcha.php` it is …
1. … IMHO not ideal to rely on a chance of 0 or 1 to try to rotate the image or not and …
2. … to rotate the background exclusively with an angle of 180° or not (0°)
Thatswhy I replaced the rotation (with `imagerotate`) with a mirroring with the function `imageflip`, which provides three modes (horizontal, vertical and both at once) to generate the resulting image. The new solution decides if …

Fix failing imagerotate with 180° rotation (rare corner case)

---

includes/functions.inc.php

Until now we set the character set encoding of the database connection with the query `SET NAMES utf8mb4`. As [the manual page of the function `mysqli_set_names`](https://www.php.net/manual/de/mysqli.set-charset.php) states, is the use of the function preferred over the use of the above mentioned query for this purpose because the function changes more than only the charset of the connection itself.
**But** the function does not set a collation for the connection (defines the sorting of ordered query results). When the collation is not explicitely set to a defined value, the default value configured on the specific server is used instead.
This is described [in](https://www.php.net/manual/de/mysqli.set-charset.php#122858) [a](https://www.php.net/manual/de/mysqli.set-charset.php#121067) …

Set the character encoding with the proper PHP function 

---

includes/functions.inc.php
themes/default/style.css
themes/default/style.min.css

Introduction of the BB-Codes `[ins]`, `[del]` and `[s]` for the corresponding HTML-elements `<ins>`, `<del>` and `<s>`.
At this time we will not introduce a setting to activate these BB-Codes and also no UI for buttons to insert the codes into a posting. Nevertheless, it is possible to include the BB-Codes in a posting. They will automatically converted to the corresponding HTML-elements.
This will solve #697.

BB-Codes for marking subsequent changes in a posting

---

update/update_2.4.19-2.5.php

In a former state the WHERE-clause for the search for the possibly existing obsolete indexes `user_type` and `user_name` in the userdata table worked with `LIKE 'user_%'`. Because this could theoretically affect further indexes, beginning with `user_`, that could be created by a forum operator, we changed the syntax to search the exact names with `IN('user_type', 'user_name')`. Doing this I forgot to remove the keyword `LIKE` from the WHERE-clause. So the first fix in this pull request is to remove LIKE from the query.

Further PR for fixes in the upgrade script

---

includes/index.inc.php
includes/main.inc.php

When installing a forum and upgrading it to the current code for testing purposes, the main overview page quitted with an error message, that told me, a query failed because of the use of a column in the ORDER BY clause, that was not part of the SELECT part of the query. The first error affected the query to select the IDs of the opening postings (use of `sticky` and `time`) and the second the data to create the thread trees (use of `time`).
It seems to be an issue of the configuration of the database server (in my cae MySQL 8.0). It's also possible that this is an unintended consequence of the database optimisations or a combination of both. This cannot be determined in a hurry. I hope, I found every case.
The first issue was solved by adding the columns `sticky` and `time` to the query. …

Fix for database errors, caused by missing columns in the select-part of queries

---

update/update_2.4.19-2.5.php

The table was defined without a primary key. This can cause the multiple presence of the rows under special circumstances (in example after a reimport of the data into the table). This in turn can mean that not all existing values can be managed and utilised.
With the change the old table will be renamed, a new table with a PK will be created and the existing data will be imported into the new table.  With the use of one `INSERT` with `GROUP_CONCAT()` of the data it is ensured, that the content of the column `list` of every row with the specified value for the column `name` gets part of only one row with the specified `name` value. The last step is to drop the old table from the database.
**Known issue**: when entries are part of multiple rows in the old table, they will be there multiple …

Rework of the database table mlf2_banlists

---

includes/admin.inc.php

The banlists can contain duplicated entries. Remove duplicates with the PHP function `array_unique` before saving the lists to the database.
This fixes #727

De-duplicate the content of the banlists

---

includes/index.inc.php

Add the column `mlf2_entries.last_reply` to the select-block of the query to get all thread-ids to be able to order the result by that column.
fixes #731

Put forgotten column for ORDER BY clause into the SELECT-section of the query

---

update/update_2.4.19-2.5.php

For changing the database engine of tables to InnoDB we collect the affected table names with a query. For this purpose I wrote a list with all possible table names in an `IN()`. Problem was, that I listed *every* possible table name in its representation in the array `$db_settings` even the table and with it its element in the array does not exist in the current version, that should be upgraded. With a correspondingly configured error level, an error was generated due to the non-existent array elements in `$db_settings`.
I now collect the *existing* table name entries in `$db_settings` in a loop and inserting the resulting imploded string to the query. This ensures to not using non existing table names.

Collect the table names from the existing entries in $db_settings

---

themes/default/subtemplates/admin.inc.tpl
themes/default/subtemplates/login.inc.tpl
themes/default/subtemplates/register.inc.tpl
themes/default/subtemplates/user_edit_email.inc.tpl
themes/default/subtemplates/user_edit_pw.inc.tpl
themes/default/subtemplates/user_remove_account.inc.tpl

When displaying a password input field as plain text (switching input type from password to text) browsers may send the value to a server not only for spellchecking but more recently also to AI. This may be a local browser based but can also be a server based solution. This would result in another cause of exposure of passwords to probably external services.
The new attribute `writingsuggestions` with the value `false` prevents AI based suggestions (exposure to the web based AI-service) for the password, if the password is shown as plaintext. This is necessary because the default value of `writingsuggestions` is `true`. Whoever made this decision for whatever reason should be struck by lightning while taking a dump!

Change: add new attribute "writingsuggestions" with value "false"

---

themes/default/style.css
themes/default/style.min.css

The CSS-rules for the many different states of a subject link [^1] contains many identical, repeated definitions. Because of the new introduced class `.subject` *which is present in every case*, it is now possible to move these rules to this class and to deduplicate them in the definition blocks for the state specific classes.
[^1]: i.e. `thread`, `thread-locked`, `thread-sticky`, `thread-sticky-locked` and so on

Unify the common CSS rules for the subject link under the class `.subject`

---

includes/posting.inc.php
themes/default/subtemplates/posting_flag_ham.inc.tpl
themes/default/subtemplates/posting_report_spam.inc.tpl

With PR #746 we added `time` elements for the timestamp in the subject lines. I forgot to add the ISO formatted datetime to the `datetime` attribute in the `time` element in the report spam template. Furthermore I completely forgot to add the new HTML-structure of the subject line to the flag ham template. Both is solved with the changes in this PR.

ISO-timestamps in the subject line for report spam and flag ham pages

---

includes/admin.inc.php
includes/upload_image.inc.php

Added *.webp and also *.svg to file types, that are listed in the browsing view. The script is yet not prepared to allow uploads of SVGs but also the image browsing view in the administration area allows SVG and we should handle it the same way everywhere.
The file types are now checked in one regular expression instead of using dedicated expressions for each individual file type.
This fixes #766 and superseeds #768

Make WebP images appear in the uploaded-images browsing view

---

themes/default/upload_image.tpl

Beginning with solving the bug, mentioned in issue #770, I found several further issues in the template, that made a complete rework necessary. Doing this, a bunch of further small issues was solved within.
In detail, the following changes were made.
- The view of already uploaded images packaged in a list.
- The other views, displaying the just now uploaded image or the one when confirming the deletion of an image, got the same list structure, even only one image is shown.
- The images, that should be clickable, are packed in a button because buttons are interactive elements while images are not.
- The inline JavaScript code to insert an image into a posting got removed.
- The function `insertCode` to insert an image into a posting was reworked to reflect the change of the HTML-structure …

Complete rework of the template of the upload popup

---

update/update_2.4.19-2.5.php

Until now we utilised the classic PHP functions `mysqli_errno` and `mysqli_error` to display errors in the queries of the upgrade script. But because we use transactions in a try-catch-block to process all queries of an upgrade step, these functions does not contain any information in the catch block.
With using the information from the exception object to display MySQL error information (`$e->getLine()`, `$e->getCode()` and the always present `$e->getMessage()`), we now get the number of the first line of the affected query, the error code from the MySQL-server and the servers error message.

Missing information about MySQLi-errors in the upgrade script

---

includes/posting.inc.php
themes/default/subtemplates/posting.inc.tpl

- Repaired the HTML-structure of `div.wrapper`.
- Added the `time` element to the author data of the preview.
- Repaired the alternative text attributes of the icons for the link to the homepage and to the e-mail-contact-form.
Especially for the last point it is relevant to mention, that the language section `thread_entry`, which was loaded previously in line 2 of the template file, does not exist in any of the language files. I now load the existing section `user`, which provides appropriate alternative text snippets in the keys `email` and `homepage`.
These text snippets are IMHO in itself much more understandable than the text icons `⌂` and `@` which are in use in other places for the same purpose where they are supplemented by the snippets, which are used here as alternative texts, as …

Fixes for the errors in the preview section of the posting template, reported in #778

---

includes/admin.inc.php
lang/arabic.lang
lang/chinese.lang
lang/chinese_traditional.lang
lang/croatian.lang
lang/danish.lang
lang/english.lang
lang/french.lang
lang/german.lang
lang/italian.lang
lang/norwegian.lang
lang/russian.lang
lang/spanish.lang
lang/swedish.lang
lang/tamil.lang
lang/turkish.lang
themes/default/style.min.css
themes/default/subtemplates/admin.inc.tpl

Currently the upload management in the admin area lists all images and make it possible to select multiple images of an image-list-page for removal from the file system. That's all.
Managing images should be more than this. Since version 20220508.1 the forum software stores informations about the uploaded images in a database table (user-id of the uploading user (`NULL` for not registered users), filename, time of uploading). For providing information in example about the use of an image in postings in the future, the managment UI must be flexible and not directed to *one* certain function.
For this reason, I have extended the `$images` array, renamed the checkbox and also made the label text a little more general. This serves to prepare for the expansion of the upload management …

Restructuring the upload management

---

lang/arabic.lang

Those was untranslated because of the non existing arabic translation at the time of adding them to the other languages.

Add missing strings to the Arabic translation

---

includes/admin.inc.php

There was two bugs in the merged code for pull request #789.
1. When checking the entries in the database against the array of uploaded images, all images was marked as managed in the uploads table in case of not a single entry in this table. The code has not taken this case of an empty result of the table query into account.
2. The code to delete (a) selected image(s) should delete also the entry for an image, if present. The query searched the filename in the column `filename` which was renamed to `pathname`. This led to a silent database error, what led to `mysqli_query` returning `false`, what led to not fulfilling the requirement `if ($rDelUploadEntry !== false)` to delete the image file from the file system.
The two commits in this PR fixes these bugs.

Fixes for the upload management enhancements

---

themes/default/subtemplates/login_pw_forgotten.inc.tpl

Added the attributes `autofocus` and `required` to the input field for the e-mail-address and changed its type from `text` to `email`.
Fixes #790

Fix #790: apply the changes to the template for sending an e-mail in case of a forgotten password

---

includes/upload_image.inc.php

I replaced the column name "filename" with the new name "pathname" with the latest upgrade to version 20250323.1. The purpose is to describe with the column name, that the column can not only store filenames but also relative paths for the cae of splitting the directories for uploads to yearly or monthly dirs. For details see also #789 and #798.
Doing this I missed one query with the old column name. The project forum user Fritz [reported the bug](https://mylittleforum.net/forum/index.php?id=18918) in the project forum (in German language).

Fix for wrong column name "filename" in the uploads management table

---

themes/default/subtemplates/entry.inc.tpl

Remove the superfluous comma, mentioned in #806. It's already present in the translation strings and has not to be repeated in the template.

Fix issue 806, remove a superfluous comma

---

update/update_2.4.19-2.5.php

When altering the definition for the database table column `mlf2_tags.id` to make it an unsigned integer for the upgrade to version 20250323.1 I forgot to notice the attribute `AUTO_INCREMENT` as part of the redefinition of the column. Because of this it was therefore possible to add tags to postings and bookmarks, that already existed in the database but it was impossible to create completely new tags.
Adding the attribute `AUTO_INCREMENT` fixes this bug.

Broken upgrade for adding new tags top postings and bookmarks

---

update/update_2.4.19-2.5.php

Set `mlf2_uploads.uploader` to `NULL` if the user who created the image upload was deleted from `mlf2_userdata` inbetween the time of the upload and the upgrade of the forum to a version that supports the foreign key connection between `mlf2_uploads.uploader` and `mlf2_userdata.user_id`.

Fix entries for uploads from users who no longer exist

---

themes/default/images/rss-logo.svg
themes/default/main.tpl
themes/default/style.min.css
themes/default/subtemplates/entry.inc.tpl
themes/default/subtemplates/thread.inc.tpl
themes/default/subtemplates/thread_linear.inc.tpl

With replacing this icon that is in use in a link list in the page footer as well as below the postings outside a list was an opportunity to create a standardized infrastructure for icons on links and buttons, which can be assigned to the icons now stored in HTML instead of as CSS background images by assigning the class `icon` to the images.
Additionally, with adding the icons to the HTML sources, the fiddling with repositioning of icons as background images in the CSS source for right to left written languages will have an end when done.

Replace the old RSS icon with a SVG icon

---

includes/entry.inc.php
includes/thread.inc.php
themes/default/subtemplates/entry.inc.tpl
themes/default/subtemplates/thread.inc.tpl
themes/default/subtemplates/thread_linear.inc.tpl

One thing, that triggered me since ages, is the doubling of the links to lock or unkock the complete thread under postings. In the single posting view every single posting repeats these two links, in the threaded views only the opening posting provides these links.
The left locking link, named "lock" would lock only the posting and if the posting is locked, it changes it's name to "unlock". The two links on the right-hand side of the screenshot are the links for locking and unlocking the entire thread, which is what this is about. 
Once, *before* he created the MLF-repository on Github, I submitted Alex a diff of a patch to unify the two links into one but he rejected the patch with a reason that I don't remember. Regardless of his reasoning, which can no longer be reconstructed, I think …

Unifying the thread locking links in the options list for postings

---

themes/default/images/manage-marked-postings.svg
themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/index.inc.tpl
themes/default/subtemplates/index_table.inc.tpl

This pull request adds SVG icons to the moderation menu in the sidbars of the overview pages. It adds one new icon and reuses four other icons, that are already in use at other places. Because of the nested font size definitions the icons preliminary will be displayed in a small 12 pixel grid. This will change when the font size definitions will be reworked and thereby simplified.
This pull request is related to #808.

SVG icons for the moderation menu

---

js/main.js
js/posting.js
themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/posting.inc.tpl

As discussed [in the project forum](https://mylittleforum.net/forum/index.php?id=19006) (ff., German language) it is in several forum and board systems common to show the formatting buttons of postings with icons only and without text.
With this pull request we are implementing this too. Beside hiding the text, which remains accessible for screen reader users, the appearance of the posting formatting buttons is now controlled with CSS and no longer left to the operating systems. Beside this the `div#format-bar` is from now on hidden and will only be displayed if the JavaScript function to generate the buttons is working. Until then the box was shown with not working JavaScript with the  height of one text line.

Display the posting buttons with the icons only

---

includes/user.inc.php

Providing `NULL` values to functions `intval` and `htmlspecialchars` is reported as deprecated with PHP 8.1. Initialising the variable `$last_posting` in `includes/user.inc.php` with `NULL`, filling in the result of the previous database request only if the result has one content line and checking the variable for its content to decide if to process it for the template engine or not.

No null value for array $last_posting

---

themes/default/style.css
themes/default/style.min.css

During the work on implementing the new SVG icons and setting them into the HTML source code I removed the class `.stronglink` and its formatting for links that should be admirable on a page. This affected the links to the posting form in the footer of a posting and also the non-breadcrumb-links in `#subnav-1` in the subnavigation bar. I reformatted them without the removed class by selecting the links under a posting as link in the div of class `reply` (selector `.posting-footer .reply a`) respectively by making all childs of `#subnav-1` bold (selector `#subnav-1 *`).

Fix the bold font formatting for the links and breadcrumbs in the subnavigation bar and for the reply link 

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/entry.inc.tpl

I found a few further issues with the icon code.
First there was a doubled definition for flipping icon images in case of displaying the forum in a language that is written from right to left. A second issue was the not flipped icon in front of the subject line of the currently displayed posting in the thread tree below the posting in the single posting view.

Further fixes for the new SVG icons

---

includes/admin.inc.php
lang/arabic.lang
lang/chinese.lang
lang/chinese_traditional.lang
lang/croatian.lang
lang/danish.lang
lang/english.lang
lang/french.lang
lang/german.lang
lang/italian.lang
lang/norwegian.lang
lang/russian.lang
lang/spanish.lang
lang/swedish.lang
lang/tamil.lang
lang/turkish.lang
themes/default/subtemplates/admin.inc.tpl
update/update_2.4.19-2.5.php

Until now one gets displayed a list of files to upload and within this list items with files to delete in the second step of a forum upgrade. While *a few* obsolete images, templates or JavaScript files which remains in an installation, it is no good style to have obsolete server scripts or *masses* of obsolete images on the server.
In the light of replacing almost all pixel grid images of the default theme with SVG images there are really *many* image files to be deleted. All these entries would land in the single list and would blow up the list with that many files to delete. In the list of files that need to be uploaded ***and*** files that need to be deleted, there is a risk that individual items will be overlooked. On the one hand, entries may be forgotten, and on the other hand, …

Forum upgrade script: separate the list of files to delete from the list of files to update

---

themes/default/style.css
themes/default/style.min.css
themes/default/subtemplates/search.inc.tpl

The advanced search form has a bad styling after changing its HTML structure from putting the form elements side by side with putting them into table cells to residing in separate `div` elements. After this change the form was only formatted by the browser default styling.
The styling has been significantly improved with making the form itself being a flexbox and putting the `div` side by side again which can flow into new lines in narrow browser viewports.

Formatting of the advanced search form

---

includes/functions.inc.php
includes/main.inc.php

In the functions `getVersionPHP` and `getVersionDB` the code determines the installed versions of the PHP interpreter respectively the database server. These information should be displayed in the admin panel.
See also #861 ands #860

Add functions to determine the versions of PHP and the Database server
